---
name: 01 Azure Landing Zones Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: ExjobbOA/alz-mgmt-templates/.github/workflows/ci-template.yaml@v1.0.0
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      parameters_file_name: config/platform.json
